name: Frontend Testing

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
    - uses: actions/checkout@v3
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - run: npm install
      name: Install dependencies
    - run : pip install robotframework
      name: Install robotframework
    - run : pip install robotframework-faker
      name: Install Faker library
    - run : pip install --upgrade robotframework-seleniumlibrary
      name: Install Selenium
    - run : sudo apt-get install chromium-chromedriver
      name : Install Chrome driver
    - run: npm run test
      name: Running unit tests
  system_tests:
    name: System Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
    - uses: actions/checkout@v3
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - run: echo todo
      name: To do
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
