name: Frontend Testing

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
    - uses: actions/checkout@v3
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - run: npm install
      name: Install dependencies
    - run : pip install robotframework
      name: Install robotframework
    - run : pip install robotframework-faker
      name: Install Faker library
    - run : pip install --upgrade robotframework-seleniumlibrary
      name: Install Selenium
    - run : sudo apt-get install chromium-chromedriver
      name: Install Chrome driver
    - name: "Ubuntu Xvfb"
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: |
        export DISPLAY=:13.0
        Xvfb :13 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        # xauth with complain unless ~/.Xauthority exists
        touch ~/.Xauthority
        # To view a listing of the .Xauthority file, enter the following 
        xauth list
        # fluxbox 
        fluxbox &
    - run: npm run test
      name: Running unit tests
  system_tests:
    name: System Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
    - uses: actions/checkout@v3
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - run: echo todo
      name: To do
