name: Frontend Testing

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
   runs-on: ubuntu-latest
   steps :
    - uses: actions/checkout@v2
    - name: Execute tests
      uses: joonvena/robotframework-docker-action@v0.1
      env:
        BROWSER: chrome
        ROBOT_TESTS_DIR: ${{ github.workspace }}/tests
        ROBOT_REPORTS_DIR: ${{ github.workspace }}/tests/results
    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: ${{ github.workspace }}/tests/results
  system_tests:
    name: System Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
    - uses: actions/checkout@v3
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - run: echo todo
      name: To do
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
